# must be unique in a given SonarQube instance
sonar.login=sqp_547c16bade4be3e970911f0705bb6709c2849931
sonar.projectKey=msc-web

# --- optional properties ---

# defaults to project key
sonar.projectName=msc-web
# defaults to 'not provided'
sonar.projectVersion=1.0
 
# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=src/app
 
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.ispec.ts
#/home/renetravez/.sonar/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner -Dsonar.login=sqp_06f1645838f444c7481c05ae470d99256ee9f8c0